<?php

namespace Gaskata\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuthUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthUserRepository extends EntityRepository
{
}
