# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # Have to have a discussion with myself (or you, if you read this and have
    # an opinion.
    app.authentication:
        class: Gaskata\Utils\Authentication
        arguments: ['@service_container' ]

